// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmlvqqtkoowckobztscn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbHZxcXRrb293Y2tvYnp0c2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Njk3NTQsImV4cCI6MjA3MzM0NTc1NH0.do4b2fKeelxHiRQJHtdbA5p2CsXMwCZkCym3Gqo9dzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});